// react/src/App.tsx
import AddNote from "./components/AddNote";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import ToDoList from "./components/ToDoList";

const App = () => {
  return (
    <div className="min-h-screen theme relative">
      <Navbar />
      <div className="container mx-auto p-3 flex flex-col gap-6">
        <AddNote />
        <ToDoList />
      </div>
      <Footer />
    </div>
  );
};

export default App;

// angular/src/app/app.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './layout/header/header.component';
import { FooterComponent } from './layout/footer/footer.component';
import { AddtodoComponent } from './components/addtodo/addtodo.component';
import { TodoslistComponent } from './components/todolist/todolist.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, HeaderComponent, FooterComponent, AddtodoComponent,TodoslistComponent],
  templateUrl: './app.component.html',
  encapsulation: ViewEncapsulation.None,
})
export class AppComponent {
  title = 'todo-app';
}

<div class="min-h-screen theme relative">
  <app-header></app-header>
  <div class="container mx-auto p-3 flex flex-col gap-6">
    <app-addtodo></app-addtodo>
    <app-todoslist></app-todoslist>
  </div>
  <app-footer></app-footer>
</div>
