// src/components/ToDoList.tsx
import { DeleteIcon, PenIcon, Trash2, XIcon } from "lucide-react";
import { useAppSelector } from "../app/hooks";
import useTodo from "../hooks/useTodo";
import Modal from "./Modal";
import React, { useState } from "react";
type Props = {
  setEdit?: React.Dispatch<React.SetStateAction<ToDoProp | undefined>>;
};

const ToDoList = ({ setEdit }: Props) => {
  const { deleteTodo, editTodos } = useTodo();
  const [open, setOpen] = useState(false);
  const [selectedTodo, setSelectedTodo] = useState<ToDoProp | null>(null);
  const todos = useAppSelector((st) => st.todos.data);
  if (!todos) {
    return <div>No ToDoList</div>;
  }
  console.log(selectedTodo);
  return (
    <>
      <div key={JSON.stringify(todos)} className="flex flex-wrap gap-6">
        {todos.map((todo, i) => {
          return (
            <React.Fragment key={i}>
              <div
                onClick={() => {
                  setOpen(true);
                  setSelectedTodo(todo);
                }}
                className="border relative p-3 rounded-lg cursor-pointer shadow flex justify-between flex-[3] min-w-80"
              >
                <div className="">
                  <p className="text-xl font-semibold mb-4">{todo.title}</p>
                  <p className=" line-clamp-6">{todo.content}</p>
                </div>
                {/* <div className="btns flex items-center gap-4 absolute right-3">
                  <div className="btn" onClick={() => setEdit && setEdit(todo)}>
                    <PenIcon />
                  </div>
                  <div className="btn danger" onClick={() => deleteTodo(todo)}>
                    <Trash2 />
                  </div>
                </div> */}
              </div>
            </React.Fragment>
          );
        })}
      </div>
      <Modal open={open} closeModel={() => setOpen(false)}>
        {selectedTodo && (
          <div className="relative rounded-lg flex flex-col justify-between flex-[3] min-w-80">
            <div className="p-3">
              <input
                type="text"
                onChange={(e) =>
                  setSelectedTodo((prev) => {
                    const updatedTodo = {
                      title: e.target.value,
                      content: selectedTodo.content,
                    };
                    editTodos(updatedTodo);
                    return updatedTodo;
                  })
                }
                defaultValue={selectedTodo.title}
                className="text-xl font-semibold mb-4 outline-none w-full"
              />
              <textarea
                onChange={(e) =>
                  setSelectedTodo((prev) => {
                    const updatedTodo = {
                      title: prev?.title||"",
                      content: e.target.value,
                    };
                    editTodos(updatedTodo);
                    return updatedTodo;
                  })
                }
                rows={10}
                className="w-full outline-none h-fit"
                defaultValue={selectedTodo.content}
              ></textarea>
            </div>
            <div className="borde-t-2 p-3 box-border bg-gray-100 sticky bottom-0 w-full flex justify-between">
              <div
                className="text-red-500 cursor-pointer w-fit"
                onClick={() => {
                  deleteTodo(selectedTodo);
                  setOpen(false);
                }}
              >
                <Trash2 />
              </div>
              <button
                className="btn danger w-fit"
                onClick={() => setOpen(false)}
              >
                Close
              </button>
            </div>
          </div>
        )}
      </Modal>
    </>
  );
};

export default ToDoList;

// angular/src/app/components/todolist/todolist.component.ts
import { NgFor } from '@angular/common';
import { Component, effect } from '@angular/core';
import { TodosProps, View, todos } from '../../services/todos.service';
import { TodoCardComponent } from '../todo-card/todo-card.component';

@Component({
  selector: 'app-todoslist',
  standalone: true,
  imports: [TodoCardComponent, NgFor],
  templateUrl: './todolist.component.html',
})
export class TodoslistComponent {
  todos: TodosProps[] = todos();
  constructor() {
    console.log(todos);
  }

  viewType: View = 'list';
}

@if(searchParams){
<div class="flex items-center justify-between mb-4">
  <h2>
    Showing result of :
    <span class="text-primary font-bold cursor-pointer">
      {{ searchParams }}
    </span>
  </h2>
  <button (click)="resetFilter()" class="btn">Show all</button>
</div>
} @if (filteredTodos.length == 0) {
<div class="p-3 text-center rounded-md font-bold text-xl py-4">
  @if(searchParams){
  <p>No todos found</p>
  <button (click)="resetFilter()" class="btn mt-4">Clear Search</button>
  }
</div>
}

<div class="flex flex-wrap gap-4 justify-center">
  @for (todo of (searchParams?filteredTodos:todos); track todo.id) {
  <div
    [ngClass]="{
      'w-[99%] md:w-[45%] lg:w-[23%]': viewType == 'grid',
      'w-full': viewType == 'list'
    }"
  >
    <todo-card
      [isSelcted]="todo.id == selectedTodo?.id"
      (click)="openModel(todo)"
      (removeListItem)="removeListItem($event)"
      (markAsDoneEmit)="markAsDone($event)"
      [todo]="todo"
    ></todo-card>
  </div>
  } @empty { @if(!searchParams){
  <div class="w-full">
    <h1 class="text-2xl font-semibold text-center w-full">No todos found</h1>
  </div>
  } }
</div>

<model-cmp [open]="showModel" (closeModal)="closeModel()">
  @if(selectedTodo){
  <div
    class="relative rounded-lg flex flex-col justify-between flex-[3] min-w-80"
  >
    <div class="p-3">
      <input
        #titleInput
        type="text"
        [defaultValue]="selectedTodo.title"
        (blur)="editTitle()"
        class="text-xl font-semibold mb-4 outline-none w-full bg-transparent"
      />
      <div
        #contentInput
        contenteditable
        (blur)="editContent()"
        class="outline-none z-10"
      ></div>
    </div>
    <div
      class="theme p-3 box-border border-t dark:border-brown sticky bottom-0 w-full flex justify-between"
    >
      <div class="text-red-500 cursor-pointer w-fit">
        <i class="fa-solid fa-trash" id="trash-icon" (click)="removeListItem(selectedTodo.id)"></i>
      </div>
      <button (click)="closeModel()" class="btn danger w-fit">Close</button>
    </div>
  </div>
  }
</model-cmp>
