// angular/src/app/components/todolist/todolist.component.ts
import { NgFor, CommonModule } from '@angular/common';
import { Component, ElementRef, ViewChild, inject } from '@angular/core';
import { TodosProps, TodosService, View } from '../../services/todos.service';
import { TodoCardComponent } from '../todo-card/todo-card.component';
import { ModelComponent } from '../model/model.component';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-todoslist',
  standalone: true,
  imports: [TodoCardComponent, CommonModule, ModelComponent],
  templateUrl: './todolist.component.html',
})
export class TodoslistComponent {
  private activeRoute = inject(ActivatedRoute);
  private router = inject(Router);
  todos: TodosProps[] = [];
  viewType: View = 'grid';
  showModel = false;
  selectedTodo: TodosProps | null = null;
  searchParams = '';
  filteredTodos: TodosProps[] = [];
  @ViewChild('contentInput', { static: false }) contentInput!: ElementRef;
  @ViewChild('titleInput', { static: false }) titleInput!: ElementRef;

  constructor(private todoservice: TodosService) {
    this.todoservice.todos.subscribe(
      (todos) => (this.todos = (todos || []).reverse())
    );
    this.todoservice.viewType.subscribe((type) => (this.viewType = type));
    this.activeRoute.queryParams.subscribe((params) => {
      this.searchParams = params['search'];
      this.filteredTodos = this.todos.filter(
        (todo) =>
          todo.title.toLowerCase().includes(this.searchParams.toLowerCase()) ||
          todo.content.toLowerCase().includes(this.searchParams.toLowerCase())
      );
    });
  }

  editTitle() {
    if (this.selectedTodo) {
      const todo = this.selectedTodo;
      todo.title = this.titleInput.nativeElement.value;
      this.todoservice.editTodos(todo);
    }
  }

  editContent() {
    if (this.selectedTodo) {
      const todo = this.selectedTodo;
      todo.content = this.contentInput.nativeElement.innerText;
      this.todoservice.editTodos(todo);
    }
  }

  openModel(todo: TodosProps) {
    this.showModel = true;
    this.selectedTodo = todo;
    this.contentInput.nativeElement.innerText = todo.content;
  }

  closeModel() {
    this.showModel = false;
    this.selectedTodo = null;
  }

  resetFilter() {
    this.filteredTodos = [];
    this.router.navigate(['/']);
  }
}

@if(searchParams){
<div class="flex items-center justify-between mb-4">
  <h2>
    Showing result of :
    <span class="text-primary font-bold cursor-pointer">
      {{ searchParams }}
    </span>
  </h2>
  <button (click)="resetFilter()" class="btn">Show all</button>
</div>
}

@if (filteredTodos.length == 0) {
<div class="p-3 text-center rounded-md font-bold text-xl py-4">
  @if(searchParams){
  <p>No todo found in the search result !!</p>
  <button (click)="resetFilter()" class="btn mt-4">Clear Search</button>
  }
</div>
}

<div class="flex flex-wrap gap-4 justify-center">
  @for (todo of (searchParams?filteredTodos:todos); track todo.id) {
  <div [ngClass]="{'w-[99%] md:w-[45%] lg:w-[23%]': viewType == 'grid','w-full':viewType == 'list'}">
    <todo-card [isSelcted]="todo.id == selectedTodo?.id" (click)="openModel(todo)" [todo]="todo"></todo-card>
  </div>
  } @empty {
  @if(!searchParams){
  <div class="w-full">
    <h1 class="text-2xl font-semibold text-center w-full">No todo Found !!</h1>
  </div>
  }
  }
</div>

<model-cmp [open]="showModel" (closeModal)="closeModel()">
  @if(selectedTodo){
  <div class="relative rounded-lg flex flex-col justify-between flex-[3] min-w-80">
    <div class="p-3">
      <input #titleInput type="text" [defaultValue]="selectedTodo.title" (blur)="editTitle()"
        class="text-xl font-semibold mb-4 outline-none w-full bg-transparent" />
      <div #contentInput contenteditable (blur)="editContent()" class="outline-none z-10"></div>
    </div>
    <div class="theme p-3 box-border border-t dark:border-brown sticky bottom-0 w-full flex justify-between">
      <div class="text-red-500 cursor-pointer w-fit">
        <i class="fa-solid fa-trash"></i>
      </div>
      <button (click)="closeModel()" class="btn danger w-fit">Close</button>
    </div>
  </div>
  }
</model-cmp>

// react/src/components/ToDoList.tsx
import { Trash2 } from "lucide-react";
import React, { useEffect, useState } from "react";
import { useAppSelector } from "../app/hooks";
import useTodo from "../hooks/useTodo";
import Modal from "./Modal";
import NoteInput from "./NoteInput";
import TodoCard from "./TodoCard";
import { useSearchParams, Navigate, useNavigate } from "react-router-dom";

const ToDoList = () => {
  const todos = useAppSelector((st) => st.todos.data);
  const [todosData, setTodosData] = useState<ToDos[]>(todos);
  const { deleteTodo, editTodos } = useTodo();
  const [open, setOpen] = useState(false);
  const navigate = useNavigate();
  const [queryParameters] = useSearchParams();
  const searchParams = queryParameters.get("search");
  const [selectedTodo, setSelectedTodo] = useState<ToDos>({
    id: "",
    title: "",
    content: "",
  });

  useEffect(() => {
    if (searchParams) {
      const filter = todos.filter(
        (todo) =>
          todo.title.toLowerCase().includes(searchParams.toLowerCase()) ||
          todo.content.toLowerCase().includes(searchParams.toLowerCase())
      );
      setTodosData(filter);
    } else {
      setTodosData(todos);
    }
  }, [searchParams, todos]);

  const resetFilter = () => {
    navigate("/");
    return;
  };

  if (todosData.length == 0) {
    return (
      <div className="p-3 text-center rounded-md font-bold text-xl py-4">
        <p>
          {searchParams
            ? "No todo found in the search result !!"
            : " No Todo Found !!"}
        </p>
        {searchParams && (
          <button onClick={resetFilter} className="btn mt-4">
            Clear Search
          </button>
        )}
      </div>
    );
  }
  return (
    <>
      {searchParams && (
        <div className="flex items-center justify-between">
          <h2>
            Showing result of :{" "}
            <span className="text-primary font-bold cursor-pointer">
              {searchParams}
            </span>
          </h2>
          <button onClick={resetFilter} className="btn">
            Show all
          </button>
        </div>
      )}
      <div className="flex flex-wrap justify-center align-top gap-6">
        {todosData.map((todo, i) => (
          <TodoCard
            key={i}
            todo={todo}
            open={open}
            setOpen={() => setOpen(true)}
            selectedTodo={selectedTodo}
            setSelectedTodo={() => setSelectedTodo(todo)}
          />
        ))}
      </div>
      <Modal open={open} closeModel={() => setOpen(false)}>
        {selectedTodo && (
          <div className="relative rounded-lg flex flex-col justify-between flex-[3] min-w-80">
            <div className="p-3">
              <input
                type="text"
                defaultValue={selectedTodo.title}
                className="text-xl font-semibold mb-4 outline-none w-full bg-transparent"
                onBlur={() => editTodos(selectedTodo)}
                onChange={(e) =>
                  setSelectedTodo((prev) => ({
                    ...prev,
                    title: e.target.value,
                  }))
                }
              />
              <NoteInput
                value={selectedTodo.content}
                onBlur={() => editTodos(selectedTodo)}
                onChange={(value) =>
                  setSelectedTodo((prev) => ({ ...prev, content: value }))
                }
              />
            </div>
            <div className="borde-t-2 p-3 box-border border-t dark:border-brown sticky bottom-0 w-full flex justify-between">
              <div
                className="text-red-500 cursor-pointer w-fit"
                onClick={() => {
                  deleteTodo(selectedTodo.id);
                  setOpen(false);
                }}
              >
                <Trash2 />
              </div>
              <button
                className="btn danger w-fit"
                onClick={() => setOpen(false)}
              >
                Close
              </button>
            </div>
          </div>
        )}
      </Modal>
    </>
  );
};

export default ToDoList;
